version: '3.8'

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data/data/db
    restart: unless-stopped
volumes:
  mongodb-data: