spring:
  main:
    banner-mode: false
  data:
    mongodb:
      uri: mongodb://localhost:27017/weatherDB
      auto-index-creation: true
weather:
  url: http://api.weatherapi.com/v1
security:
  salt: "GH$LS1$#ghGEOUIY#12sdgsdhSD46hgO"
server:
  port: 8080
  address: 0.0.0.0



